import Head from "next/head";
import { Kosugi_Maru } from "next/font/google";

const font = Kosugi_Maru({ weight: "400", subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>cycleOn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${font.className}`}>
        {/* <div className={styles.description}>
          <p>
            your biking companion&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a href="home" target="_blank">
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div> */}
        <div class="header">
          <img src="/logo.png" href="#index" id="logo"></img>
          <div class="navbar">
            <li href="#aboutCycleOn">What is cycleOn?</li>
            <li href="#WhoIsCycleOn">Who is cycleOn?</li>
            <li href="#useCycleOn">How can I use it?</li>
            <button>
              <img src="/bike.png"></img>
              <a>Sign up here to plan your route</a>
            </button>
          </div>
        </div>
        {/* from here I wasnt able to check the code as npm run xyz didnt work  */}
        <div class="map">
          <br></br>
          <br></br>
          <a>place map here</a>
          <br></br>
          <br></br>
        </div>
        <div class="signup">
          <form>
            <label for="name">What is your name?</label>
            <br />
            <input type="text" id="name" name="name" value="Your name"></input>
            <br />
            <label for="user">Please enter a username:</label>
            <br />
            <input
              type="text"
              id="user"
              name="username"
              value="choose your username"
            ></input>
            <br />
            <label for="email">Please enter your email address:</label> <br />
            <input
              type="email"
              id="email"
              name="email"
              value=" your email address"
            ></input>
          </form>
        </div>

        <div class="login"></div>
      </main>
    </>
  );
}
